#pragma once

enum error_code {
    SUCCESS = 0,
    SEND_SUCCESS = 1,
    READ_SUCCESS = 2,
    PING_SUCCESS = 3,
    OPEN_SUCCESS = 4,
    SET_SUCCESS = 5,
    START_SUCCESS = 6,
    END_SUCCESS = 7,

    SEND_ERROR = 100,
    READ_ERROR = 101,
    TIMEOUT_ERROR = 102,
    SOCK_ERROR = 103,
    PING_ERROR = 104,
    SOMETHING_NOT_FOUND = 105,
    CANT_OPEN_SOMETHING = 106,
};